#!bin/bash

MERGE_THRESHOLD_MT=100000000
MERGE_RATIO_MT=0

MERGE_THRESHOLD_SMT=50000000
MERGE_RATIO_SMT=0

OUTPUT_MT_VS_SMT="outputs/output_mt_vs_smt.csv"


./hybrid_c_int $MERGE_THRESHOLD_MT $MERGE_RATIO_MT > $OUTPUT_MT_VS_SMT
./hybrid_c_int $MERGE_THRESHOLD_SMT $MERGE_RATIO_SMT >> $OUTPUT_MT_VS_SMT
./hybrid_c_str $MERGE_THRESHOLD_MT $MERGE_RATIO_MT >> $OUTPUT_MT_VS_SMT
./hybrid_c_str $MERGE_THRESHOLD_SMT $MERGE_RATIO_SMT >> $OUTPUT_MT_VS_SMT
./hybrid_c_url $MERGE_THRESHOLD_MT $MERGE_RATIO_MT >> $OUTPUT_MT_VS_SMT
./hybrid_c_url $MERGE_THRESHOLD_SMT $MERGE_RATIO_SMT >> $OUTPUT_MT_VS_SMT

